"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "zh" | "en";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: Translation;
};

export const translations = {
  en: {
    nav: {
      ai: "AI",
      quiz: "Quiz",
      report: "Report",
      admin: "Admin",
      home: "Home",
      languageLabel: "Language",
      chinese: "中文",
      english: "EN",
    },
    home: {
      title: "Clinically interpretable fundus image AI research system",
      subtitle:
        "A GitHub-ready project for diabetic retinopathy classification, lesion detection, Grad-CAM visualization, doctor testing, structured reporting, and paper reproduction.",
      start: "Start AI Analysis",
      previewLabel: "fundus analysis preview",
      riskModerate: "Risk: Moderate",
      confidence: "Confidence: 0.93",
      modules: [
        {
          title: "AI Detection",
          text: "Upload a fundus image and generate a structured AI report.",
        },
        {
          title: "Doctor Quiz",
          text: "Review 100 fundus images and compare answers with AI output.",
        },
        {
          title: "Clinical Report",
          text: "View the report format used by the API and paper workflow.",
        },
      ],
    },
    ai: {
      title: "AI Detection",
      intro:
        "Upload one retinal fundus image. The API returns diagnosis, lesion candidates, heatmap path, risk level, and recommendation.",
      chooseImage: "Choose fundus image",
      analyzing: "Analyzing...",
      run: "Run AI Analysis",
      requestFailed: "Analysis request failed",
      unknownError: "Unknown error",
      result: "Result",
      waiting: "The structured report will appear here after analysis.",
      demoMode: "Demo mode: trained weights were not found.",
      diagnosis: "Diagnosis",
      confidence: "Confidence",
      riskLevel: "Risk level",
      lesions: "Lesions",
      recommendation: "Recommendation",
    },
    quiz: {
      title: "Doctor Quiz",
      intro:
        "Select a diabetic retinopathy grade for each of 100 fundus images. Connect this page to Supabase when real images are ready.",
      image: "Image",
      save: "Save Response",
      saved: "Response saved locally for demo.",
      next: "Next Image",
      grades: ["No DR", "Mild", "Moderate", "Severe", "Proliferative"],
    },
    report: {
      title: "Structured AI Report",
      intro: "Clinical research report format generated from classification, YOLO detection, and Grad-CAM output.",
      diagnosis: "Diagnosis",
      diagnosisValue: "Moderate diabetic retinopathy",
      confidence: "Confidence",
      lesionEvidence: "Lesion evidence",
      lesionValue: "Exudate, hemorrhage",
      riskLevel: "Risk level",
      riskValue: "Moderate",
      recommendation: "Recommendation",
      recommendationValue: "Recommend ophthalmology follow-up and repeat imaging according to local guidelines.",
      disclaimerTitle: "Research Disclaimer",
      disclaimer:
        "This output is generated by a prototype system for research and education. It is not a certified medical diagnosis.",
    },
    medical: {
      "No diabetic retinopathy": "No diabetic retinopathy",
      "Mild diabetic retinopathy": "Mild diabetic retinopathy",
      "Moderate diabetic retinopathy": "Moderate diabetic retinopathy",
      "Severe diabetic retinopathy": "Severe diabetic retinopathy",
      "Proliferative diabetic retinopathy": "Proliferative diabetic retinopathy",
      "Demo result - model weights missing": "Demo result - model weights missing",
      Low: "Low",
      Moderate: "Moderate",
      High: "High",
      "Recommend urgent ophthalmology review and confirmatory clinical examination.":
        "Recommend urgent ophthalmology review and confirmatory clinical examination.",
      "Recommend ophthalmology follow-up and repeat imaging according to local guidelines.":
        "Recommend ophthalmology follow-up and repeat imaging according to local guidelines.",
      "Recommend routine screening follow-up. Clinical judgment remains required.":
        "Recommend routine screening follow-up. Clinical judgment remains required.",
      "Research prototype only. Not for standalone clinical diagnosis.":
        "Research prototype only. Not for standalone clinical diagnosis.",
    },
  },
  zh: {
    nav: {
      ai: "AI检测",
      quiz: "医生测试",
      report: "临床报告",
      admin: "后台管理",
      home: "首页",
      languageLabel: "语言",
      chinese: "中文",
      english: "EN",
    },
    home: {
      title: "可解释的眼底影像医学AI研究系统",
      subtitle:
        "一个可直接上传 GitHub 的糖尿病视网膜病变分类、病灶检测、Grad-CAM 可视化、医生测试、结构化报告和论文复现实验项目。",
      start: "开始AI检测",
      previewLabel: "眼底图像分析预览",
      riskModerate: "风险：中等",
      confidence: "置信度：0.93",
      modules: [
        {
          title: "AI检测",
          text: "上传一张眼底照片，生成结构化AI分析报告。",
        },
        {
          title: "医生测试",
          text: "完成100张眼底图像判读，并与AI结果进行对比。",
        },
        {
          title: "临床报告",
          text: "查看API和论文流程使用的结构化报告格式。",
        },
      ],
    },
    ai: {
      title: "AI检测",
      intro:
        "上传一张视网膜眼底图像。API会返回诊断结果、疑似病灶、热力图路径、风险等级和建议。",
      chooseImage: "选择眼底图像",
      analyzing: "分析中...",
      run: "运行AI检测",
      requestFailed: "分析请求失败",
      unknownError: "未知错误",
      result: "检测结果",
      waiting: "分析完成后，结构化报告会显示在这里。",
      demoMode: "演示模式：未找到已训练模型权重。",
      diagnosis: "诊断结果",
      confidence: "置信度",
      riskLevel: "风险等级",
      lesions: "疑似病灶",
      recommendation: "建议",
    },
    quiz: {
      title: "医生测试",
      intro:
        "请为100张眼底图像逐张选择糖尿病视网膜病变分级。真实图像准备好后，可以把本页面连接到 Supabase 数据库。",
      image: "图像",
      save: "保存答案",
      saved: "答案已在演示模式下本地保存。",
      next: "下一张图像",
      grades: ["无DR", "轻度", "中度", "重度", "增殖期"],
    },
    report: {
      title: "结构化AI报告",
      intro: "由分类模型、YOLO病灶检测和Grad-CAM解释结果生成的临床研究报告格式。",
      diagnosis: "诊断结果",
      diagnosisValue: "中度糖尿病视网膜病变",
      confidence: "置信度",
      lesionEvidence: "病灶证据",
      lesionValue: "硬性渗出、出血",
      riskLevel: "风险等级",
      riskValue: "中等",
      recommendation: "建议",
      recommendationValue: "建议进行眼科随访，并根据当地指南安排复查眼底影像。",
      disclaimerTitle: "研究声明",
      disclaimer: "本结果由科研和教学用途的原型系统生成，不属于已认证的医学诊断结论。",
    },
    medical: {
      "No diabetic retinopathy": "无糖尿病视网膜病变",
      "Mild diabetic retinopathy": "轻度糖尿病视网膜病变",
      "Moderate diabetic retinopathy": "中度糖尿病视网膜病变",
      "Severe diabetic retinopathy": "重度糖尿病视网膜病变",
      "Proliferative diabetic retinopathy": "增殖期糖尿病视网膜病变",
      "Demo result - model weights missing": "演示结果：缺少模型权重",
      Low: "低",
      Moderate: "中等",
      High: "高",
      "Recommend urgent ophthalmology review and confirmatory clinical examination.":
        "建议尽快进行眼科专科复查和临床确认。",
      "Recommend ophthalmology follow-up and repeat imaging according to local guidelines.":
        "建议进行眼科随访，并根据当地指南安排复查影像。",
      "Recommend routine screening follow-up. Clinical judgment remains required.":
        "建议按常规筛查流程随访，最终仍需结合临床判断。",
      "Research prototype only. Not for standalone clinical diagnosis.":
        "仅用于科研原型展示，不能单独作为临床诊断依据。",
    },
  },
} as const;

type Translation = (typeof translations)[Language];

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("zh");

  useEffect(() => {
    const saved = window.localStorage.getItem("fundusx-language");
    if (saved === "zh" || saved === "en") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem("fundusx-language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language],
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}

export function translateMedicalText(text: string | undefined, language: Language) {
  if (!text) return "";
  const medical = translations[language].medical as Record<string, string>;
  return medical[text] || text;
}
