import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export default function ReportPage() {
  return (
    <main className="shell compact">
      <Link className="backLink" href="/"><ArrowLeft size={18} /> Home</Link>
      <section className="report">
        <div className="reportHeader">
          <FileText size={26} />
          <div>
            <h1>Structured AI Report</h1>
            <p>Clinical research report format generated from classification, YOLO detection, and Grad-CAM output.</p>
          </div>
        </div>
        <div className="reportBody">
          <div className="metricRow"><span>Diagnosis</span><strong>Moderate diabetic retinopathy</strong></div>
          <div className="metricRow"><span>Confidence</span><strong>0.930</strong></div>
          <div className="metricRow"><span>Lesion evidence</span><strong>Exudate, hemorrhage</strong></div>
          <div className="metricRow"><span>Risk level</span><strong>Moderate</strong></div>
          <h2>Recommendation</h2>
          <p>Recommend ophthalmology follow-up and repeat imaging according to local guidelines.</p>
          <h2>Research Disclaimer</h2>
          <p>This output is generated by a prototype system for research and education. It is not a certified medical diagnosis.</p>
        </div>
      </section>
    </main>
  );
}
